name: restartServer
on: [push]
jobs:
 check-bats-version:
   runs-on: ubuntu-latest
   steps:
      
     - name: Sleep for 100 seconds
       uses: jakejarvis/wait-action@master
       with:
        time: '100s'
    

     - name: Deploy Stage
       uses: fjogeleit/http-request-action@v1
       with:
        url: 'curl -k -v https://api.gotestpro.com:8443/rcteaf-api/api/external/cicd/execute/2348637?apiKey=bf5d3f4249e54e59ab7a537cfbbcf404'
        method: 'GET'
